name: Deploy on Merge to Main

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged_to_main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is approved
        id: check_approval
        uses: reviewdog/action-check-approval@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR is from the same repository
        id: check_fork
        run: echo ::set-output name=from_fork::${{ github.event.pull_request.head.repo.full_name != github.repository }}

      - name: Exit if PR is not approved or from a fork
        run: |
          if [ "${{ steps.check_approval.outputs.approved }}" != 'true' ] || [ "${{ steps.check_fork.outputs.from_fork }}" == 'true' ]; then
            echo "PR is not approved or from a fork. Exiting."
            exit 0
          fi

      - uses: actions/checkout@v2
        # - uses: actions/setup-node@v2
      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "$SSH_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa $SSH_HOST >> ~/.ssh/known_hosts
        env:
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
    
    
      - name: Build Docker image
        run: docker build -t prospectamundi_front_image -f ./Dockerfile .

      - name: Try to create a new folder
        run: ssh $SSH_USERNAME@$SSH_HOST "mkdir -p downloads"
        env:
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
            SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Try to remove an old compacted image
        run: ssh $SSH_USERNAME@$SSH_HOST "rm -f /home/ubuntu/apps/downloads/prospectamundi_front_image.tar"
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      
      - name: Try to stop and remove old container
        run: |
            ssh $SSH_USERNAME@$SSH_HOST "sudo docker stop prospectamundi_front || true && sudo docker rm prospectamundi_front || true"
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}


      - name: Push Docker image to server
        run: |
            docker save -o prospectamundi_front_image.tar prospectamundi_front_image
            scp prospectamundi_front_image.tar $SSH_USERNAME@$SSH_HOST:/home/ubuntu/apps/downloads/prospectamundi_front_image.tar
            ssh $SSH_USERNAME@$SSH_HOST "sudo docker rmi prospectamundi_front_image || true"
            ssh $SSH_USERNAME@$SSH_HOST "sudo docker load -i /home/ubuntu/apps/downloads/prospectamundi_front_image.tar"
        env:
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            nome_da_imagem: prospectamundi/prospectamundi_front_image
            tag: latest
 

      - name: Deploy the image to container
        run: ssh $SSH_USERNAME@$SSH_HOST "sudo docker compose -f ./apps/docker-compose.yml up -d prospectamundi_front"
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
